apiVersion: v1
kind: Config
clusters:
- name: local
  cluster:
    server: "https://103.185.52.42:6443"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzTlRrM016QXlNVGt3SGhjTk1qVXhNREEyTURVMU5qVTVXaGNOTXpVeE1EQTBNRFUxTmpVNQpXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzTlRrM016QXlNVGt3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFRV1BPMkRQTjBQbHlCVVN4U2xpaEZUV2lBTGpydG1BN20vbU9Ta2xYSkUKNXd4ZmRPRTVxQ0M2STNMTEFEZ3NCOENHZnhXUGVZK2laRUU0d3BxNTVnTlJvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVTVRTWtidVUvZ1BocGpDbWhnNDhZCi9wL21rUDR3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUloQU5Yc2tlbDMrV0IyTGxhWTRrb0VvMnBvV0tvUzcvNHcKVHRudURBeGZmK2Y4QWlBeDIrT0F6Ky9jbU5nY29YbzU3Q25YQ2s0ZXRmbTZIL2RFeXlBVGhGSUtsZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
contexts:
- name: cipta-works
  context:
    cluster: local
    namespace: cipta-works
    user: cipta-works-sa
current-context: cipta-works
users:
- name: cipta-works-sa
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6ImhHd0RPTEdOY1M0aFJ1YVB4dFdxNFFMbF9CSEZfLW9xdkEwSFdIT19yMkEifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJjaXB0YS13b3JrcyIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJjaXB0YS13b3Jrcy1zYS10b2tlbiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJjaXB0YS13b3Jrcy1zYSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjBjNjE3MTE1LTU3ZmUtNDFhMC1hMWEyLTIxYmE1YTg4MzkxNiIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpjaXB0YS13b3JrczpjaXB0YS13b3Jrcy1zYSJ9.GzVAM9OYwt0Yn5aCzDUbHzNWFJlNoQIfXvdwyUhhUZ-eNrXJQwPPZGle7bwSxdEWT5x2P31wjcjh3JEmChhSV0mkcmacbxBH8tEDVJKR3n8C7tH1HtpfqU8GsK-Syi7-6o2PpqZ_ngrGXbat8QBollQWoyleFu4R6aFHDfUl1R2Zfh75It0OpFr8c9UpKkXiC35H8-rekSTvwHLz6GTY6CBHuZUAtxdfpQhfAxQXI7vnFC0Cyeph_LZrxFLCXPYmYnSjenRwua-VoPW211oU8FNEE7HKS6d3IPNScltr9ms1V7Ui0sBc99hj1_hpg2eqaS0vBVgHzUqCmNyl3yZHqg
